"use strict";

const cagney_frames = {
  intro: [
    "../../assets/Cagney/Intro/Intro_08.png",
    "../../assets/Cagney/Intro/Intro_09.png",
    "../../assets/Cagney/Intro/Intro_10.png",
    "../../assets/Cagney/Intro/Intro_11.png",
    "../../assets/Cagney/Intro/Intro_12.png",
    "../../assets/Cagney/Intro/Intro_13.png",
    "../../assets/Cagney/Intro/Intro_14.png",
    "../../assets/Cagney/Intro/Intro_15.png",
    "../../assets/Cagney/Intro/Intro_16.png",
    "../../assets/Cagney/Intro/Intro_17.png",
    "../../assets/Cagney/Intro/Intro_18.png",
    "../../assets/Cagney/Intro/Intro_19.png",
    "../../assets/Cagney/Intro/Intro_20.png"
  ],
  idle: [
    "../../assets/Cagney/Idle/Idle_01.png",
    "../../assets/Cagney/Idle/Idle_02.png",
    "../../assets/Cagney/Idle/Idle_03.png",
    "../../assets/Cagney/Idle/Idle_04.png",
    "../../assets/Cagney/Idle/Idle_05.png",
    "../../assets/Cagney/Idle/Idle_06.png",
    "../../assets/Cagney/Idle/Idle_07.png",
    "../../assets/Cagney/Idle/Idle_08.png",
    "../../assets/Cagney/Idle/Idle_09.png",
    "../../assets/Cagney/Idle/Idle_10.png",
    "../../assets/Cagney/Idle/Idle_11.png",
    "../../assets/Cagney/Idle/Idle_12.png",
    "../../assets/Cagney/Idle/Idle_13.png",
    "../../assets/Cagney/Idle/Idle_14.png",
    "../../assets/Cagney/Idle/Idle_15.png",
    "../../assets/Cagney/Idle/Idle_16.png",
    "../../assets/Cagney/Idle/Idle_17.png",
    "../../assets/Cagney/Idle/Idle_18.png",
    "../../assets/Cagney/Idle/Idle_19.png",
    "../../assets/Cagney/Idle/Idle_20.png",
    "../../assets/Cagney/Idle/Idle_21.png",
    "../../assets/Cagney/Idle/Idle_22.png",
    "../../assets/Cagney/Idle/Idle_23.png",
    "../../assets/Cagney/Idle/Idle_24.png"
  ],
  create_object: [
    "../../assets/Cagney/Creating Object/Create_01.png",
    "../../assets/Cagney/Creating Object/Create_02.png",
    "../../assets/Cagney/Creating Object/Create_03.png",
    "../../assets/Cagney/Creating Object/Create_04.png",
    "../../assets/Cagney/Creating Object/Create_05.png",
    "../../assets/Cagney/Creating Object/Create_06.png",
    "../../assets/Cagney/Creating Object/Create_07.png",
    "../../assets/Cagney/Creating Object/Create_08.png",
    "../../assets/Cagney/Creating Object/Create_09.png",
    "../../assets/Cagney/Creating Object/Create_10.png",
    "../../assets/Cagney/Creating Object/Create_11.png",
    "../../assets/Cagney/Creating Object/Create_12.png",
    "../../assets/Cagney/Creating Object/Create_13.png",
    "../../assets/Cagney/Creating Object/Create_14.png",
    "../../assets/Cagney/Creating Object/Create_15.png",
    "../../assets/Cagney/Creating Object/Create_16.png",
    "../../assets/Cagney/Creating Object/Create_17.png",
    "../../assets/Cagney/Creating Object/Create_18.png",
    "../../assets/Cagney/Creating Object/Create_19.png",
    "../../assets/Cagney/Creating Object/Create_20.png",
    "../../assets/Cagney/Creating Object/Create_21a.png",
    "../../assets/Cagney/Creating Object/Create_22.png",
    "../../assets/Cagney/Creating Object/Create_23.png",
    "../../assets/Cagney/Creating Object/Create_24.png",
    "../../assets/Cagney/Creating Object/Create_25.png",
    "../../assets/Cagney/Creating Object/Create_26.png",
    "../../assets/Cagney/Creating Object/Create_x.png"
  ],
  death: [
    "../../assets/Cagney/Death/Death_01.png",
    "../../assets/Cagney/Death/Death_02.png",
    "../../assets/Cagney/Death/Death_03.png",
    "../../assets/Cagney/Death/Death_04.png",
    "../../assets/Cagney/Death/Death_05.png",
    "../../assets/Cagney/Death/Death_06.png",
    "../../assets/Cagney/Death/Death_07.png",
    "../../assets/Cagney/Death/Death_08.png",
    "../../assets/Cagney/Death/Death_09.png",
    "../../assets/Cagney/Death/Death_10.png",
    "../../assets/Cagney/Death/Death_11.png",
    "../../assets/Cagney/Death/Death_12.png"
  ],
  firing_seeds: [
    "../../assets/Cagney/Firing Seeds/FS_01.png",
    "../../assets/Cagney/Firing Seeds/FS_02.png",
    "../../assets/Cagney/Firing Seeds/FS_03.png",
    "../../assets/Cagney/Firing Seeds/FS_04.png",
    "../../assets/Cagney/Firing Seeds/FS_05.png",
    "../../assets/Cagney/Firing Seeds/FS_06.png",
    "../../assets/Cagney/Firing Seeds/FS_07.png",
    "../../assets/Cagney/Firing Seeds/FS_08.png",
    "../../assets/Cagney/Firing Seeds/FS_09.png",
    "../../assets/Cagney/Firing Seeds/FS_10.png",
    "../../assets/Cagney/Firing Seeds/FS_11.png",
    "../../assets/Cagney/Firing Seeds/FS_12.png",
    "../../assets/Cagney/Firing Seeds/FS_13.png",
    "../../assets/Cagney/Firing Seeds/FS_14.png",
    "../../assets/Cagney/Firing Seeds/FS_15.png",
    "../../assets/Cagney/Firing Seeds/FS_16.png",
    "../../assets/Cagney/Firing Seeds/FS_17.png",
    "../../assets/Cagney/Firing Seeds/FS_18.png",
    "../../assets/Cagney/Firing Seeds/FS_19.png",
    "../../assets/Cagney/Firing Seeds/FS_20.png",
    "../../assets/Cagney/Firing Seeds/FS_21.png",
    "../../assets/Cagney/Firing Seeds/FS_22.png"
  ]
};
