"use strict";

const cagney_frames = {
  intro: [
    "../../assets/Cagney/Intro/resized/Intro_08_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_09_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_10_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_11_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_12_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_13_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_14_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_15_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_16_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_17_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_18_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_19_optimized.png",
    "../../assets/Cagney/Intro/resized/Intro_20_optimized.png"
  ],
  idle: [
    "../../assets/Cagney/Idle/resized/Idle_01_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_02_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_03_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_04_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_05_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_06_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_07_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_08_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_09_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_10_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_11_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_12_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_13_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_14_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_15_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_16_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_17_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_18_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_19_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_20_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_21_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_22_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_23_optimized.png",
    "../../assets/Cagney/Idle/resized/Idle_24_optimized.png"
  ],
  create_object: [
    "../../assets/Cagney/Creating Object/resized/Create_01_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_02_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_03_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_04_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_05_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_06_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_07_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_08_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_09_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_10_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_11_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_12_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_13_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_14_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_15_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_16_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_17_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_18_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_19_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_20_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_21a_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_22_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_23_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_24_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_25_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_26_optimized.png",
    "../../assets/Cagney/Creating Object/resized/Create_x_optimized.png"
  ],
  death: [
    "../../assets/Cagney/Death/resized/Death_01_optimized.png",
    "../../assets/Cagney/Death/resized/Death_02_optimized.png",
    "../../assets/Cagney/Death/resized/Death_03_optimized.png",
    "../../assets/Cagney/Death/resized/Death_04_optimized.png",
    "../../assets/Cagney/Death/resized/Death_05_optimized.png",
    "../../assets/Cagney/Death/resized/Death_06_optimized.png",
    "../../assets/Cagney/Death/resized/Death_07_optimized.png",
    "../../assets/Cagney/Death/resized/Death_08_optimized.png",
    "../../assets/Cagney/Death/resized/Death_09_optimized.png",
    "../../assets/Cagney/Death/resized/Death_10_optimized.png",
    "../../assets/Cagney/Death/resized/Death_11_optimized.png",
    "../../assets/Cagney/Death/resized/Death_12_optimized.png"
  ],
  firing_seeds: [
    "../../assets/Cagney/Firing Seeds/resized/FS_01_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_02_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_03_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_04_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_05_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_06_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_07_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_08_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_09_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_10_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_11_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_12_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_13_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_14_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_15_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_16_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_17_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_18_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_19_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_20_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_21_optimized.png",
    "../../assets/Cagney/Firing Seeds/resized/FS_22_optimized.png"
  ]
};
