export class AnimationFrames {
  public static cuphead: any = {
    idle: [
      "../assets/cuphead/Idle/resized/cuphead_idle_0001_optimized.png",
      "../assets/cuphead/Idle/resized/cuphead_idle_0002_optimized.png",
      "../assets/cuphead/Idle/resized/cuphead_idle_0003_optimized.png",
      "../assets/cuphead/Idle/resized/cuphead_idle_0004_optimized.png",
      "../assets/cuphead/Idle/resized/cuphead_idle_0005_optimized.png",
      "../assets/cuphead/Idle/resized/cuphead_idle_0004_optimized.png",
      "../assets/cuphead/Idle/resized/cuphead_idle_0003_optimized.png",
      "../assets/cuphead/Idle/resized/cuphead_idle_0002_optimized.png"
    ],
    run: {
      normal: [
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0001_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0002_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0003_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0004_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0005_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0006_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0007_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0008_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0009_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0010_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0011_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0012_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0013_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0014_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0015_optimized.png",
        "../assets/cuphead/Run/Normal/resized/cuphead_run_0016_optimized.png"
      ],
      gun: [
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0001_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0002_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0003_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0004_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0005_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0006_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0007_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0008_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0009_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0010_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0011_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0012_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0013_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0014_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0015_optimized.png",
        "../assets/cuphead/Run/Shooting/Straight/resized/cuphead_run_shoot_0016_optimized.png"
      ]
    },
    jump: [
      "../assets/cuphead/Jump/resized/cuphead_jump_0001_optimized.png",
      "../assets/cuphead/Jump/resized/cuphead_jump_0002_optimized.png",
      "../assets/cuphead/Jump/resized/cuphead_jump_0003_optimized.png",
      "../assets/cuphead/Jump/resized/cuphead_jump_0004_optimized.png",
      "../assets/cuphead/Jump/resized/cuphead_jump_0005_optimized.png",
      "../assets/cuphead/Jump/resized/cuphead_jump_0006_optimized.png",
      "../assets/cuphead/Jump/resized/cuphead_jump_0007_optimized.png",
      "../assets/cuphead/Jump/resized/cuphead_jump_0008_optimized.png"
    ],
    death: [
      "../assets/cuphead/Death/resized/cuphead_death_body_0001_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0002_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0003_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0004_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0005_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0006_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0007_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0008_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0009_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0010_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0011_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0012_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0013_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0014_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0015_optimized.png",
      "../assets/cuphead/Death/resized/cuphead_death_body_0016_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0001_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0002_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0003_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0004_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0005_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0006_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0007_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0008_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0009_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0010_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0011_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0012_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0013_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0014_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0015_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0016_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0017_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0018_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0019_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0020_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0021_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0022_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0023_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_ghost_0024_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0001_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0002_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0003_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0004_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0005_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0006_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0007_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0008_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0009_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0010_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0011_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0012_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0013_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0014_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0015_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0016_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0017_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0018_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0019_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0020_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0021_optimized.png",
      "../assets/cuphead/Ghost/resized/cuphead_revive_0022_optimized.png"
    ],
    shoot: [
      "../assets/cuphead/Shoot/Straight/resized/cuphead_shoot_straight_0001_optimized.png",
      "../assets/cuphead/Shoot/Straight/resized/cuphead_shoot_straight_0002_optimized.png",
      "../assets/cuphead/Shoot/Straight/resized/cuphead_shoot_straight_0003_optimized.png"
    ]
  };

  public static cagney: any = {
    intro: [
      "../assets/Cagney/Intro/resized/Intro_08_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_09_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_10_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_11_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_12_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_13_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_14_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_15_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_16_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_17_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_18_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_19_optimized.png",
      "../assets/Cagney/Intro/resized/Intro_20_optimized.png"
    ],
    idle: [
      "../assets/Cagney/Idle/resized/Idle_01_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_02_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_03_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_04_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_05_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_06_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_07_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_08_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_09_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_10_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_11_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_12_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_13_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_14_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_15_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_16_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_17_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_18_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_19_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_20_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_21_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_22_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_23_optimized.png",
      "../assets/Cagney/Idle/resized/Idle_24_optimized.png"
    ],
    create_object: [
      "../assets/Cagney/Creating Object/resized/Create_01_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_02_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_03_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_04_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_05_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_06_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_07_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_08_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_09_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_10_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_11_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_12_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_13_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_14_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_15_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_16_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_17_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_18_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_19_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_20_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_21a_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_22_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_23_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_24_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_25_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_26_optimized.png",
      "../assets/Cagney/Creating Object/resized/Create_x_optimized.png"
    ],
    death: [
      "../assets/Cagney/Death/resized/Death_01_optimized.png",
      "../assets/Cagney/Death/resized/Death_02_optimized.png",
      "../assets/Cagney/Death/resized/Death_03_optimized.png",
      "../assets/Cagney/Death/resized/Death_04_optimized.png",
      "../assets/Cagney/Death/resized/Death_05_optimized.png",
      "../assets/Cagney/Death/resized/Death_06_optimized.png",
      "../assets/Cagney/Death/resized/Death_07_optimized.png",
      "../assets/Cagney/Death/resized/Death_08_optimized.png",
      "../assets/Cagney/Death/resized/Death_09_optimized.png",
      "../assets/Cagney/Death/resized/Death_10_optimized.png",
      "../assets/Cagney/Death/resized/Death_11_optimized.png",
      "../assets/Cagney/Death/resized/Death_12_optimized.png"
    ],
    firing_seeds: [
      "../assets/Cagney/Firing Seeds/resized/FS_01_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_02_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_03_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_04_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_05_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_06_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_07_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_08_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_09_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_10_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_11_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_12_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_13_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_14_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_15_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_16_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_17_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_18_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_19_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_20_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_21_optimized.png",
      "../assets/Cagney/Firing Seeds/resized/FS_22_optimized.png"
    ]
  };

  public static skills: any = {
    ray: ["../assets/resized/cuphead_ray_optimized.png"],
    missile: [
      "../assets/Cagney/Firing Seeds/Seed Missiles/Blue/resized/Missile_B_01_optimized.png",
      "../assets/Cagney/Firing Seeds/Seed Missiles/Blue/resized/Missile_B_02_optimized.png",
      "../assets/Cagney/Firing Seeds/Seed Missiles/Blue/resized/Missile_B_03_optimized.png",
      "../assets/Cagney/Firing Seeds/Seed Missiles/Blue/resized/Missile_B_04_optimized.png",
      "../assets/Cagney/Firing Seeds/Seed Missiles/Blue/resized/Missile_B_05_optimized.png",
      "../assets/Cagney/Firing Seeds/Seed Missiles/Blue/resized/Missile_B_06_optimized.png"
    ],
    seed_missile: [
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_01_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_02_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_03_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_04_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_05_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_06_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_07_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_08_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_09_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_10_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_11_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_12_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_13_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_14_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_15_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_16_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_17_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/Seed/resized/Seed_Fall_A_18_optimized.png"
    ],
    pollen: [
      "../assets/Cagney/Pollen/resized/Pollen_A_1_optimized.png",
      "../assets/Cagney/Pollen/resized/Pollen_A_2_optimized.png",
      "../assets/Cagney/Pollen/resized/Pollen_A_3_optimized.png",
      "../assets/Cagney/Pollen/resized/Pollen_A_4_optimized.png"
    ],
    boomerang: [
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_01_optimized.png",
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_02_optimized.png",
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_03_optimized.png",
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_04_optimized.png",
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_05_optimized.png",
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_06_optimized.png",
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_07_optimized.png",
      "../assets/Cagney/Creating Object/Boomerang/resized/Boomerang_08_optimized.png"
    ],
    venus: [
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_01_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_02_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_03_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_04_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_05_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_06_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_07_A_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_07_B_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_08_A_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_08_B_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_08_C_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_09_A_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_09_B_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_10_A_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_10_B_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_11_A_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_11_B_optimized.png",
      "../assets/Cagney/Firing Seeds/Venus Flytrap/resized/Venus_12_optimized.png"
    ]
  };

}
